PageEvaluateVariables.title=Evaluate Variables
PageEvaluateVariables.description=
PageEvaluateVariables.page.title=Evaluate Variables
PageEvaluateVariables.page.description=Evaluate environment properties tool
